#!/bin/sh

LOGFILE=/var/log/clusterboot.log
PIDFILE=/var/run/clusterboot.pid

PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH

case "$1" in
    start)
        ulimit -c unlimited
        mkdir -p $(dirname $LOGFILE)
        export $(cat /etc/locale)
        clusterbootstrap $LOGFILE &
        echo $! > $PIDFILE
        ;;
    stop)
        pid=$(cat $PIDFILE)
        [ -n "$pid" ] && kill -TERM $pid
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0

